package sportlogin;
// Generated Nov 6, 2016 6:11:56 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private String user;
     private String password;
     private String sname;
     private String ssurname;
     private String sex;

    public Account() {
    }

    public Account(String user, String password, String sname, String ssurname, String sex) {
       this.user = user;
       this.password = password;
       this.sname = sname;
       this.ssurname = ssurname;
       this.sex = sex;
    }

    

    

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getSsurname() {
        return this.ssurname;
    }
    
    public void setSsurname(String ssurname) {
        this.ssurname = ssurname;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }




}


